baseURL = "https://cloudshock.io/"
languageCode = "en-us"
title = "Cloud Shock"
Subtitle = "CLOUD DEVELOPMENT FOR THE SMALL ENTERPRISE"
description = "Cloud Development Topics for the Small to Medium Sized Technology Business"
[taxonomies]
    tag = "tags"
    category = "categories"
    
